# PICloud Group 2 Deployment Phase

# Database PersistentVolumeClaim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pidev-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# Database PersistentVolume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pidev-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mysql
    
---

# Database Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidev-database
  labels:
    app: label-deployment-pidev-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-deployment-pidev-database
  template:
    metadata:
      labels:
        app: label-deployment-pidev-database
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: pidev-database
        image: mysql:latest
        ports:
        - containerPort: 3303
          name: cport-3303
        volumeMounts:
        - name: volume-pidev-database
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      volumes:
      - name: volume-pidev-database
        persistentVolumeClaim:
          claimName: pvc-pidev-database
      restartPolicy: Always

---

# Database Service ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: service-pidev-database-clusterip
  labels:
    app: label-service-pidev-database-clusterip
spec:
  selector:
    app: label-deployment-pidev-database
  ports:
  - port: 3306
    name: port-3306
    targetPort: 3306

---

# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidev-backend
  labels:
    app: label-deployment-pidev-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-deployment-pidev-backend
  template:
    metadata:
      labels:
        app: label-deployment-pidev-backend
    spec:
      containers:
      - name: pidev-backend
        image: mdjdocker/arctic4_pidev_backend:latest
        ports:
        - containerPort: 9000
          name: cport-9000
        - containerPort: 2424
          name: cport-2424
      restartPolicy: Always
  
---

# Backend Service NodePort
apiVersion: v1
kind: Service
metadata:
  name: service-pidev-backend-nodeport
  labels:
    app: label-service-pidev-backend-nodeport
spec:
  selector:
    app: label-deployment-pidev-backend
  ports:
  - port: 9000
    name: port-9000
    targetPort: 9000
    nodePort: 30001
  - port: 2424  
    name: port-2424
    targetPort: 2424
    nodePort: 30003
  type: NodePort
  
---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidev-frontend
  labels:
    app: label-deployment-pidev-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-deployment-pidev-frontend
  template:
    metadata:
      labels:
        app: label-deployment-pidev-frontend
    spec:
      containers:
      - name: pidev-frontend
        image: mdjdocker/arctic4_pidev_frontend:latest
        ports:
        - containerPort: 80
          name: cport-80
      restartPolicy: Always
    
---

# Frontend Service NodePort
apiVersion: v1
kind: Service
metadata:
  name: service-pidev-frontend-nodeport
  labels:
    app: label-service-pidev-frontend-nodeport
spec:
  selector:
    app: label-deployment-pidev-frontend
  ports:
  - port: 80 
    name: port-80
    targetPort: 80
    nodePort: 30002
  type: NodePort
  
---
