apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidev-frontend
  labels:
    app: label-deployment-pidev-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-deployment-pidev-frontend
  template:
    metadata:
      labels:
        app: label-deployment-pidev-frontend
    spec:
      containers:
      - name: pidev-frontend
        image: mdjdocker/arctic4_pidev_frontend:latest
        ports:
        - containerPort: 80
    
---

# Frontend Service NodePort

apiVersion: v1
kind: Service
metadata:
  name: service-pidev-frontend-nodeport
  labels:
    app: label-service-pidev-frontend-nodeport
spec:
  selector:
    app: label-deployment-pidev-frontend
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30002
  type: NodePort
  
---

# Frontend Service ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: service-pidev-frontend-clusterip
  labels:
    app: label-service-pidev-frontend-clusterip
spec:
  selector:
    app: label-deployment-pidev-frontend
  ports:
  - port: 80  
    targetPort: 80
  type: ClusterIP
